# Tensor Data Structures

## Introduction

1. Introduction
2. Tensors from Scratch
3. Tensor shapes and structures
4. Tensor Operations

In [1]:
"""
We can have various different tensors dimensions 1D 2D 3D ...

We can arrange our data into tensors - much like np.arrays etc.
"""

'\nWe can have various different tensors dimensions 1D 2D 3D ...\n\nWe can arrange our data into tensors - much like np.arrays etc.\n'

In [2]:
import torch
import numpy as np
import pandas as pd

/usr/local/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
torch.__version__

'1.12.0'

In [4]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [5]:
type(arr)

numpy.ndarray

In [6]:
"""
Pass in an np array to make a new Tensor w/ a copy of the original Array
NOTE: This does not make a copy of the original array, but ties it 
to the memory slot of the original array.
"""
x = torch.from_numpy(arr)

In [7]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [8]:
x.dtype

torch.int64

In [9]:
arr2d = np.arange(0.0, 12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
arr2d = arr2d.reshape(4,3)

In [11]:
x2 = torch.from_numpy(arr2d)

In [12]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [13]:
# most common function to convert numpy array to a Tensor
arr = np.arange(0,10)
my_tensor = torch.tensor(arr) # creates a new Tensor as a copy of the original np array
mh_other_tensor = torch.from_numpy(arr) # creates a new Tensor with direct link to theoriginal np array

In [14]:
"""
Creating Tensors from Scratch
"""

'\nCreating Tensors from Scratch\n'

In [15]:
new_array = np.array([1,2,3])
torch.tensor(new_array)

tensor([1, 2, 3])

In [16]:
new_array = np.array([1,2,3])
tsr = torch.Tensor(new_array)
tsr2 = torch.FloatTensor(new_array)

In [17]:
tsr2.dtype

torch.float32

In [18]:
"""
Placeholder Tensors
"""

'\nPlaceholder Tensors\n'

In [19]:
x = torch.empty(2,2,dtype=torch.float)
x

tensor([[ 0.0000e+00, -8.5899e+09],
        [ 0.0000e+00, -8.5899e+09]])

In [20]:
zeroes = torch.zeros(4,3, dtype=torch.int32)
zeroes

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [21]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [23]:
value = torch.linspace(0,18,12).reshape(4,3) # twelve linearly spaced values from 0-18
value

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [24]:
value2 = torch.tensor([1,2,3]).type(torch.float)
value2 = value.type(torch.float)
value2

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [25]:
torch.rand(4,3) # random values in a uniform distribution

tensor([[0.5065, 0.7701, 0.6339],
        [0.6205, 0.9014, 0.6738],
        [0.0780, 0.7275, 0.7722],
        [0.9995, 0.6067, 0.2902]])

In [26]:
v = torch.randn(4,3) # mean is at zero and std-deviation is a one
v

tensor([[-0.2549,  1.1783,  1.0046],
        [-0.0567,  0.6019,  1.0339],
        [-0.8573,  0.5510,  1.7752],
        [-2.3524, -1.8679, -0.5033]])

In [27]:
vv = torch.randint(low=0, high=10, size=(5,5))
vv

tensor([[0, 2, 9, 1, 2],
        [7, 6, 1, 6, 6],
        [8, 2, 0, 2, 9],
        [1, 9, 6, 0, 6],
        [6, 1, 1, 5, 0]])

In [28]:
tt = torch.randint(0, 10, (5,5))
tt

tensor([[0, 7, 7, 5, 2],
        [7, 4, 4, 0, 9],
        [1, 8, 5, 4, 1],
        [7, 2, 1, 0, 9],
        [2, 6, 2, 6, 4]])

In [29]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [30]:
x.shape

torch.Size([2, 5])

In [31]:
x_2 = torch.rand_like(x) # takes the shape off the incoming shape of the input tensor
x_2

tensor([[0.6493, 0.6856, 0.2807, 0.8828, 0.1203],
        [0.9332, 0.6756, 0.6812, 0.1432, 0.2099]])

In [32]:
x_3 = torch.rand_like(x)
x_3

tensor([[0.2371, 0.2089, 0.5519, 0.1606, 0.7845],
        [0.6807, 0.0152, 0.3783, 0.5516, 0.1157]])

In [33]:
x_4 = torch.randint_like(x,low=0, high=20)
x_4

tensor([[ 0., 11., 17., 17., 10.],
        [16., 17., 19.,  3., 12.]])

In [34]:
# reproducability w/ seeding
y = torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

# Tensor Operations

In [35]:
import torch 
import numpy as np
import pandas as pd

In [36]:
"""
Slicing
"""
x = torch.arange(0, 6, 1).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [37]:
a = x[1, 1]
t = x[:, 1] # get back all values in the 1 column from each row

In [38]:
tt = x[:, 1:]
print(tt)

# or

ta = x[:, 1].reshape(3, 1)
print(ta)

tensor([[1],
        [3],
        [5]])
tensor([[1],
        [3],
        [5]])


In [39]:
# reshape w/o changing the original data structure
a = torch.arange(0, 10, 1)
a.view(2,5)

# to reassign
a = a.view(2,5)


In [40]:
z = a.view(2, 5)
z[0] = 1000
print(z)
print(a) # notice how both changes when we use views. 

tensor([[1000, 1000, 1000, 1000, 1000],
        [   5,    6,    7,    8,    9]])
tensor([[1000, 1000, 1000, 1000, 1000],
        [   5,    6,    7,    8,    9]])


In [41]:
t = torch.arange(0, 12, 1)

In [42]:
# Infer what the second dimension should be w/ a -1 in the second parameter. 
t.view(2,-1)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [43]:
a = torch.tensor([1, 2, 3], dtype=torch.float)

In [44]:
b = torch.tensor([4, 5, 6], dtype=torch.float)

In [45]:
t = a + b
t

tensor([5., 7., 9.])

In [46]:
torch.add(a,b)

tensor([5., 7., 9.])

In [47]:
### Underscore methods are different thatn the usual methods in torch
# a = a + b
a.add_(b) # the underscore reassigns the result to itself

tensor([5., 7., 9.])

#### Dot Products and M/Mult

In [55]:
a = torch.tensor([1,2,3])
b = torch.tensor([3,4,5])
a * b

tensor([ 3,  8, 15])

In [56]:
## Dot product
aa = a.dot(b)
aa

tensor(26)

In [72]:
bb = torch.arange(0, 6, 1).reshape(2, 3)
print(bb.shape)
aa = torch.arange(6, 12, 1).reshape(3, 2)
print(aa.shape)

# matrix multiplication
torch.mm(aa, bb)

torch.Size([2, 3])
torch.Size([3, 2])


tensor([[21, 34, 47],
        [27, 44, 61],
        [33, 54, 75]])

In [73]:
# euclidian norm
x = torch.tensor([2, 3, 4, 5], dtype=torch.float)
x.norm()

tensor(7.3485)

In [80]:
x.numel() # number of elements
# or
len(x)

4