In [1]:
import numpy as np
data = np.random.random((3, 4))
print(data)

[[0.14034781 0.16588933 0.45458111 0.03548735]
 [0.07052357 0.85753233 0.20209279 0.20711937]
 [0.9283222  0.25115942 0.55365534 0.93558785]]
